# Generated by Django 4.2.7 on 2023-12-14 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_student_profile_pic'),
        ('createQuiz', '0004_questionset'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledClasses',
            fields=[
                ('enClassID', models.AutoField(primary_key=True, serialize=False)),
                ('dateEnrolled', models.DateTimeField()),
                ('classID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createQuiz.classlist')),
                ('studentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
