# Generated by Django 4.2.7 on 2023-12-15 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('classID', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=50, null=True)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('section', models.CharField(max_length=15, null=True)),
                ('enrollKey', models.CharField(max_length=20, null=True)),
                ('teacherID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TopicList',
            fields=[
                ('topicID', models.AutoField(primary_key=True, serialize=False)),
                ('topicName', models.CharField(max_length=50, null=True)),
                ('topicDescription', models.CharField(max_length=50, null=True)),
                ('classID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createQuiz.classlist')),
            ],
        ),
        migrations.CreateModel(
            name='QuizList',
            fields=[
                ('quizID', models.AutoField(primary_key=True, serialize=False)),
                ('quizName', models.CharField(max_length=50, null=True)),
                ('quizDescription', models.CharField(max_length=50, null=True)),
                ('topicID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createQuiz.topiclist')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('qName', models.CharField(max_length=50, null=True)),
                ('qDescription', models.CharField(max_length=50, null=True)),
                ('choiceA', models.CharField(max_length=50, null=True)),
                ('choiceB', models.CharField(max_length=50, null=True)),
                ('choiceC', models.CharField(max_length=50, null=True)),
                ('choiceD', models.CharField(max_length=50, null=True)),
                ('answer', models.CharField(max_length=5, null=True)),
                ('quizID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createQuiz.quizlist')),
            ],
        ),
    ]
