# Generated by Django 4.2.7 on 2023-12-11 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_student_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('classID', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=50, null=True)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('section', models.CharField(max_length=15, null=True)),
                ('enrollKey', models.CharField(max_length=20, null=True)),
                ('teacherID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
        ),
    ]
