# Generated by Django 4.2.7 on 2023-12-11 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createQuiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicList',
            fields=[
                ('topicID', models.AutoField(primary_key=True, serialize=False)),
                ('topicName', models.CharField(max_length=50, null=True)),
                ('topicDescription', models.CharField(max_length=50, null=True)),
                ('classID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createQuiz.classlist')),
            ],
        ),
    ]
