# Generated by Django 4.2.7 on 2023-12-11 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createQuiz', '0002_topiclist'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizList',
            fields=[
                ('quizID', models.AutoField(primary_key=True, serialize=False)),
                ('quizName', models.CharField(max_length=50, null=True)),
                ('quizDescription', models.CharField(max_length=50, null=True)),
                ('topicID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createQuiz.topiclist')),
            ],
        ),
    ]
