# Generated by Django 4.2.7 on 2023-12-11 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createQuiz', '0003_quizlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('qName', models.CharField(max_length=50, null=True)),
                ('qDescription', models.CharField(max_length=50, null=True)),
                ('choiceA', models.CharField(max_length=50, null=True)),
                ('choiceB', models.CharField(max_length=50, null=True)),
                ('choiceC', models.CharField(max_length=50, null=True)),
                ('choiceD', models.CharField(max_length=50, null=True)),
                ('answer', models.CharField(max_length=5, null=True)),
                ('quizID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createQuiz.quizlist')),
            ],
        ),
    ]
