# Generated by Django 4.2.7 on 2023-11-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_student_email_remove_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profiledefault.jpg', null=True, upload_to=''),
        ),
    ]
